@SETLOCAL
@IF NOT DEFINED NODE_PATH (
  @SET "NODE_PATH=C:\Users\SAKIB MONDAL\Downloads\code\node_modules\.pnpm\vite@8.0.5_@types+node@22.19.17_jiti@2.6.1\node_modules\vite\node_modules;C:\Users\SAKIB MONDAL\Downloads\code\node_modules\.pnpm\vite@8.0.5_@types+node@22.19.17_jiti@2.6.1\node_modules;C:\Users\SAKIB MONDAL\Downloads\code\node_modules\.pnpm\node_modules"
) ELSE (
  @SET "NODE_PATH=C:\Users\SAKIB MONDAL\Downloads\code\node_modules\.pnpm\vite@8.0.5_@types+node@22.19.17_jiti@2.6.1\node_modules\vite\node_modules;C:\Users\SAKIB MONDAL\Downloads\code\node_modules\.pnpm\vite@8.0.5_@types+node@22.19.17_jiti@2.6.1\node_modules;C:\Users\SAKIB MONDAL\Downloads\code\node_modules\.pnpm\node_modules;%NODE_PATH%"
)
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\vite\bin\vite.js" %*
) ELSE (
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\vite\bin\vite.js" %*
)
